Refactoring user_info_test using gomock
3scale-labs/authorino pull request #81
Opened 2021-03-31 05:39 UTC by didierofrivia

A follow up PR continuing the work made on https://github.com/3scale-labs/authorino/pull/69

2021-03-31 06:28 UTC, guicassolato requested changes
This opens up for several conflicts with #76. Rejecting for now so we have the chance to review that other PR first.

2021-03-31 08:10 UTC, didierofrivia commented
As soon https://github.com/3scale-labs/authorino/pull/76 is merged I'll resolve the conflicts

2021-04-01 09:47 UTC, guicassolato commented on pkg/config/metadata/user_info_test.go
> +type testArtifacts struct {
```suggestion
type userInfoTestData struct {
```

2021-04-01 10:02 UTC, guicassolato commented on pkg/config/metadata/user_info_test.go
> +	ta.idConfEvalMock.EXPECT().GetOIDC().Return(wrongOidc)
```suggestion
	otherOidcEvaluator, _ := identity.NewOIDC("http://other-oidc-server", ta.authCredMock)
	ta.idConfEvalMock.EXPECT().GetOIDC().Return(otherOidcEvaluator)
```

The subtle difference between "other" and "wrong" is that it wouldn't be possible to have this particular UserInfo config if there wasn't another valid OIDC config in identity. In other words, there must be 2 OIDC identity configs (both correct); it's the UserInfo metadata config that happens to be linked to one of those identity configs that is NOT the one that resolved the token.

2021-04-01 10:39 UTC, guicassolato commented on pkg/config/metadata/user_info_test.go
> +	otherOidcEvaluator, _ := identity.NewOIDC(fmt.Sprintf("http://wrongServer"), ta.authCredMock)
We should not use `fmt.Sprintf` without wildcard arguments. It was raising a warning before and I fixed it.

```suggestion
	otherOidcEvaluator, _ := identity.NewOIDC("http://wrongServer", ta.authCredMock)
```

2021-04-06 13:57 UTC, guicassolato approved these changes

2021-04-06 13:58 UTC, merged